### ISSUE TITLE
In jaco.py, line 173 TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by yongzhouwangbowen** [joshnroy/mujoco_jaco#1]
Dear Josh Roy and any other people interesting in robotics,

When I try to run the main.py, I got the error like this:

```
  0%|          | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/bowen/mujoco_jaco/main.py", line 81, in <module>
    obs, reward, done, T = env.step(np.random.randint(0, 4, env.num_actuators))
  File "/home/bowen/mujoco_jaco/jaco_arm/jaco.py", line 180, in step
    a = self.translate_action(action_int)
  File "/home/bowen/mujoco_jaco/jaco_arm/jaco.py", line 176, in translate_action
    return self.action_dict[action_int].copy()
TypeError: unhashable type: 'numpy.ndarray'
```
I do not clear that the meaning of  "self.action_dict[action_int].copy()" and how to solve it, please help me, thanks!

**Comment by Lygggggg** [comment]
hello, i met the same error with you,may i ask you have solve it?
